In [6]:
from robingrad import Tensor
import torch
from sklearn.datasets import make_regression
import numpy as np

### Dataset

In [2]:
X, y = make_regression(n_samples=200, n_features=5, n_targets=1, random_state=42)
print(X.shape)
print(y.shape)
print(X[0])
print(y[0:5])

(200, 5)
(200,)
[0.95927083 0.02451017 0.49799829 1.45114361 2.15318246]
[172.54436082 -52.9529574   -4.14935233 193.99958991 -66.96262773]


In [4]:
X_train = Tensor(X)
print(type(X_train), X_train.shape)

<class 'robingrad.tensor.Tensor'> (200, 5)


In [5]:
X_train[0]

TypeError: 'Tensor' object is not subscriptable

In [7]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[[0,1],[1]]

array([2, 5])