In [1]:
from robingrad import Tensor
import torch
from sklearn.datasets import make_regression
import numpy as np

### Dataset

In [2]:
X, y = make_regression(n_samples=200, n_features=5, n_targets=1, random_state=42)
print(X.shape)
print(y.shape)
print(X[0])
print(y[0:5])

(200, 5)
(200,)
[0.95927083 0.02451017 0.49799829 1.45114361 2.15318246]
[172.54436082 -52.9529574   -4.14935233 193.99958991 -66.96262773]


In [3]:
X_train = Tensor(X)
print(type(X_train), X_train.shape)

<class 'robingrad.tensor.Tensor'> (200, 5)


In [16]:
X_train[0:2].data

array([[ 0.95927083,  0.02451017,  0.4979983 ,  1.4511436 ,  2.1531825 ],
       [-0.07443343, -1.5702248 , -0.72713715, -0.24751863,  0.6206721 ]],
      dtype=float32)

In [17]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b = a.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a[[0,1],[1]]

array([2, 5])

In [34]:
a = torch.full((2,3),3., requires_grad=True)
print(a)
b = a.view((3,2))
print(b)
loss = b.sum()
print(loss)
loss.backward()
print(b.grad)
print(a.grad)

tensor([[3., 3., 3.],
        [3., 3., 3.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<ViewBackward0>)
tensor(18., grad_fn=<SumBackward0>)
None
tensor([[1., 1., 1.],
        [1., 1., 1.]])


/Users/marcosalvalaggio/opt/anaconda3/lib/python3.9/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:482.)
  return self._grad
